default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: check-for-fixme
        name: Check for FIXME
        description: "Check for the word FIXME in comments"
        entry: '(//|#).*(\bFIXME\b)'
        language: pygrep

      - id: black
        name: black
        entry: black
        args: ["-l 120"]
        language: python
        types: [python]
        require_serial: true

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true